### ISSUE TITLE
List of suggested location inputs has recoil behavior which prevents effective scrolling

### ISSUE THREAD

**Issue by mikewilburn** [Esri/indoor-routing-xamarin#19]
When a user is manually entering a start or end location, a list of suggested locations matching the inputted keystrokes appears. This list is helpful but troublesome to navigate, as it is partially obscured by the keyboard (which apparently can't be dismissed on iOS) and because attempting to scroll the list within the sliver of window in which it appears (tested using iPhone 4s, so reduced screen real estate) causes a recoil behavior. Reaching the bottom of the list does not seem possible.

**Comment by esreli** [comment]
This bug is fixed as of the [2.0 release](https://github.com/Esri/indoor-routing-xamarin/releases/tag/2.0.0). Closing.
