### ISSUE TITLE
Incorporate a toggle in the 'Route Me' view to reverse the start and end points

### ISSUE THREAD

**Issue by mikewilburn** [Esri/indoor-routing-xamarin#22]
This would allow users to easily reverse directions between two locations. I.e. in the case of clicking intended start location on the map, which by default defines the end location within the 'Route Me' view.

**Comment by nCastle1** [comment]
Resolved by https://github.com/Esri/indoor-routing-xamarin/pull/61

**Comment by esreli** [comment]
This feature is included in the [2.0 release](https://github.com/Esri/indoor-routing-xamarin/releases/tag/2.0.0). Closing.

![Simulator Screen Shot - iPhone 11 - 2020-08-19 at 15 14 48](https://user-images.githubusercontent.com/33433113/90695160-c5047c80-e22e-11ea-90a7-6f4783279164.png)
