### ISSUE TITLE
Add a configuration option to operate in Route mode (with network) or Locate mode (no network)

### ISSUE THREAD

**Issue by craig-mccabe** [Esri/indoor-routing-xamarin#32]
Many users want to find people/places inside buildings, but don't necessarily want or need to create a network dataset (and routes), due to the complication of that process. It would be great if the app could be configured to support either use case:

In Locate mode, you search for an employee or place, and it takes you to that location, but no route icon/option appears.

In Route mode, the app operates as it does now.

We're using this pattern in the new version of the 3D Campus Routing/Locating JavaScript 4.3 web app, and it would be awesome if the mobile app had the same split functionality.

**Comment by marastoica** [comment]
This issue has been resolved in PR #33. The route option does not show up if there is no Transportation Network inside the mmpk
