### ISSUE TITLE
Failed run project in iOS

### ISSUE THREAD

**Issue by ahmadabudawod** [Esri/indoor-routing-xamarin#34]
I was tried to test this example in my MacBook with new version of Visual Studio for Mac , but unfortunately  I got this error message below :

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Roslyn/Microsoft.CSharp.Core.targets(5,5): Error MSB6006: "csc.exe" exited with code 1. (MSB6006) (IndoorRouting.iOS)

/Volumes/Data/Root/Esri/IndoorRouting/ViewModels/LocationViewModel.cs(11,11): Error CS0246: The type or namespace name 'Esri' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (IndoorRouting.iOS)

**Comment by marastoica** [comment]
This app has not been tested yet with the new Visual Studio for Mac yet. Please try Xamarin Studio

**Comment by marastoica** [comment]
@ahmadabudawod looks like what you ran into is a bug in the latest version of Xamarin. Microsoft is providing a workaround for this. Please see the article below:

https://forums.xamarin.com/discussion/96095/stable-channel-15-2-2-service-release/p1
