### ISSUE TITLE
avoid auto-recenter when coming back to map view

### ISSUE THREAD

**Issue by ez4gis** [Esri/indoor-routing-xamarin#37]
Currently, when coming back to map view, the app automatically recenter map to current location instead of the last location. Ideally, as a user I'd expect it to stay where it was, to avoid confusion.

Precondition:
1. ensure that Location Services is enabled and turned on both on iOS device setting and in the indoor-routing app setting.

Steps to reproduce:
1. open indoor routing app
2. search or zoom to an office, tap on the room, it should display information on the card at bottom of screen
3. click on "setting" button on the top left of the screen, it should bring up the app setting model view
4. click "Cancel" to go back to map view
5. you'll notice that the map view is now recentered to user's current location, in stead of the room that was selected previously.  Sometimes, the room tapped on previously would be outside of current extent, thus not displayed on screen, which would cause confusion for user.

Expected outcome:
ideally, the map view should remain the same after user comes back.  If a user wants to recenter, he/she can always use the "Current Location" button on screen (at bottom right).

**Comment by esreli** [comment]
This is no longer an issue as of the [2.0 release](https://github.com/Esri/indoor-routing-xamarin/releases/tag/2.0.0). Closing.
