### ISSUE TITLE
Debug/Run Issue

### ISSUE THREAD

**Issue by gabermohamed** [Esri/indoor-routing-xamarin#41]
Getting "Error Internal Build Error: The given key was not present in the dictionary .ios" while trying to run the application from Visual Studio 2017 using Live Player on IPhone 7. I'm exteremly new to xamarian and i don't have any clue about the cause. I saw people taking that this can be invalid syntax in XAML files but i cannot find any XAML files
![indoor-routing](https://user-images.githubusercontent.com/40805649/42241127-8a75fe3c-7f1a-11e8-8db8-fd533b5774f8.png)

**Comment by marastoica** [comment]
Unfortunately our API does not play well with the live player. Have you tried running it in the simulator?
