### ISSUE TITLE
MMPK file is not being downloaded when using simulator iOS 13.1

### ISSUE THREAD

**Issue by MohamadMousheimish** [Esri/indoor-routing-xamarin#47]
Development Environment:
- Visual Studio for Mac version 8.3.2
- xCode 11.1

Using VS for Mac, when running the Indoors Application on iOS Simulator 12.x the applications works normally. 
However, when using simulator 13.1 the simulator keeps showing the page (Downloading Map) and it will not download the mmpk file.

**Comment by nCastle1** [comment]
@MohamadMousheimish Thanks for reporting this. I can reproduce this behavior with the latest Visual Studio for Mac and am looking into it now.

**Comment by nCastle1** [comment]
Appears to be related to https://github.com/xamarin/xamarin-macios/issues/7101. Investigating

**Comment by nCastle1** [comment]
@MohamadMousheimish If you enable code signing for the app, even when deploying to the simulator, it will work. If you do get it to work, you'll find that there are other issues with the app revealed by iOS 13; I've filed #48 and hope to be able to work on it soon. 

Thanks again for reporting this!

**Comment by MohamadMousheimish** [comment]
Automatic signing is already enabled as we can see. Any other suggestions?
![signing](https://user-images.githubusercontent.com/28274119/66626143-d557ce00-ebff-11e9-9ccd-38f0abf04d74.png)

**Comment by nCastle1** [comment]
@MohamadMousheimish I had success following the Entitlements trick mentioned in https://github.com/xamarin/xamarin-macios/issues/7101#issuecomment-537150447. I've not been able to get automatic provisioning working on my mac, so I'm not sure what it takes to force signing in that scenario - setting Entitlements.plist in the 'Custom Entitlements' field in Properties->iOS Bundle Signing may be required either way,

**Comment by nCastle1** [comment]
PR that will resolve this issue has been opened: https://github.com/Esri/indoor-routing-xamarin/pull/49

**Comment by nCastle1** [comment]
Resolved by #49
